### ISSUE TITLE
org/bouncycastle/asn1/ASN1OctetString not found on Fedora 22

### ISSUE THREAD

**Issue by KrzysiekJ** [m-click/mcpdf#8]
When I try to run `java -jar mcpdf-0.2.1-jar-with-dependencies.jar SOME_FILE`, I get the following output:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/asn1/ASN1OctetString
	at com.itextpdf.text.pdf.PdfEncryption.<init>(PdfEncryption.java:149)
	at com.itextpdf.text.pdf.PdfReader.readDecryptedDocObj(PdfReader.java:964)
	at com.itextpdf.text.pdf.PdfReader.readDocObj(PdfReader.java:1360)
	at com.itextpdf.text.pdf.PdfReader.readPdf(PdfReader.java:672)
	at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:181)
	at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:350)
	at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:370)
	at aero.m_click.mcpdf.Main.execute(Main.java:85)
	at aero.m_click.mcpdf.Main.main(Main.java:42)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.ASN1OctetString
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```
I’m using Fedora 22 branch and I have java-1.8.0-openjdk 1:1.8.0.45-31.b13.fc22 installed.

**Comment by vog** [comment]
It seems that the itextpdf library 5.5.0 doesn't work properly with Java 1.8, so I just released mcpdf-0.2.2 that uses itextpdf 5.5.5.

Could you check if that works for you? Otherwise, it may be worth a bug report at the itextpdf library.

**Comment by KrzysiekJ** [comment]
I cannot check that because the download link in README now returns 404.

**Comment by KrzysiekJ** [comment]
I’ve just built the new JAR file using Maven and the bug is still present.

**Comment by vog** [comment]
Oh sorry, that was my fault. I forgot one of the many manual steps needed in OSSRH to release something. OSSRH really demonstrates an anti-pattern here. :-(

Anyway, it's uploaded.

**Comment by vog** [comment]
That issue with the itextpdf library seems to be known:

0. [iText/BouncyCastle ClassNotFound org.bouncycastle.asn1.DEREncodable and org.bouncycastle.tsp.TimeStampTokenInfo](http://stackoverflow.com/q/10391271)
0. [java.lang.NoClassDefFoundError: org/bouncycastle/asn1/ASN1Encodable](http://stackoverflow.com/q/22513697)

**Comment by vog** [comment]
I just added more dependencies, which is the most I can do without a proper example PDF document.

Please try again with the latest master (974e800d4b9721bed654408c2541f9d1514afb83).

If that doesn't work, please try different versions of bcpkix-jdk15on and bcprov-jdk15on. That is, try versions 1.51, 1.50, 1.49 in that order.

**Comment by KrzysiekJ** [comment]
It seems that now the situation may have improved, since I get the following error:
```
com.itextpdf.text.exceptions.BadPasswordException: PdfReader not opened with owner password
See README for more information.
```
with all the versions from 1.52 to 1.49. I don’t know whether it is also a bug or a desired behavior. The file I use is located at http://www.finanse.mf.gov.pl/documents/766655/1481810/VAT-7(14)_v1-0E_2015.pdf .

**Comment by vog** [comment]
Fine, so the original issue is solved. I just release mcpdf-0.2.3 which contains the fix.

| I don’t know whether it is also a bug or a desired behavior

I believe this is the expected behaviour on an encrypted document. If you need more functionality (such as `input_pw PROMPT` or whatever you need), feel free to add another ticket describing the feature. As of now, nobody has yet taken the time to implement the `input_pw` option into mcpdf.
